# -*- coding: utf-8 -*-
"""mid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NPp_2n3sPPpdCXy0iSLpd_qaYYHz0Xw
"""

from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import re

driver = webdriver.Chrome()

data = []


for page in range(1, 31):

    url = f"https://rent.591.com.tw/list?keywords=淡水區&region=3&page={page}"
    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    texts = list(soup.stripped_strings)


    for i in range(len(texts)):

        text = texts[i]


        if "淡水區" in text and ("路" in text or "街" in text or "巷" in text):

            title = ""
            address = text
            price = ""
            area = ""
            layout = ""
            floor_info = ""
            building_type = ""


            if i >= 1:
                title = texts[i - 1]
                for j in range(i, min(i + 30, len(texts))):


                 if "元/月" in texts[j]:
                    if j >= 1:
                        price = texts[j - 1].replace(",", "")


                match = re.search(r'(\d+(\.\d+)?)\s*坪', texts[j])
                if match:
                    area = match.group(1)


                if any(x in texts[j] for x in [
                    "套房", "雅房", "獨立套房", "分租套房"
                ]):
                    layout = texts[j]


                if "/" in texts[j] and "樓" in texts[j]:
                    floor_info = texts[j]

                #
                if any(x in texts[j] for x in [
                    "公寓", "電梯大樓", "社區"
                ]):
                    building_type = texts[j]

            data.append([
                title,
                address,
                price,
                area,
                layout,
                floor_info,
                building_type
            ])

driver.quit()

df = pd.DataFrame(data, columns=[
    "標題/社區",
    "地址",
    "價格",
    "坪數",
    "房型",
    "樓層",
    "建物類型"
])

# 去重複
df = df.drop_duplicates()
df = df[df["價格"] != ""]
df = df[df["地址"] != ""]
df = df.reset_index(drop=True)
print(df)

df.to_csv("淡水租屋資料.csv", index=False, encoding="utf-8-sig")

print("已完成：淡水租屋資料.csv")